version: "3.8"

services: 
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports: 
      - 0.0.0.0:5532:5432
    volumes: 
      - ./database/data:/var/lib/postgresql/data
